version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-db-27-NoSQL-Data-Store
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - ./init-scripts/init.js:/docker-entrypoint-initdb.d/init.js:ro

  mongo-express:
    image: mongo-express
    container_name: mongo-express-27-NoSQL-Data-Store
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpassword@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: adminpassword
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  api:
    build: .
    container_name: nosql-api-27-NoSQL-Data-Store
    environment:
      MONGO_URI: mongodb://root:rootpassword@mongodb:27017
    ports:
      - "8002:8000"
    depends_on:
      - mongodb
